In [0]:
import numpy as np

In [0]:
### Making Activation Function(Sigmoid)
def activation(x):
  return 1/ ( 1 + np.exp(-x))

In [3]:
activation(2)

0.8807970779778823

In [4]:
#### Creating the input samples
training_inputs = np.array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]])
training_inputs

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [5]:
#### Creating Output Samples
training_outputs = np.array([[0],[1],[1],[0]])
training_outputs

array([[0],
       [1],
       [1],
       [0]])

In [6]:
#### Weights
np.random.seed(20)  # makes the random variables predictable
# np.random.rand(20)  # makes the random variables unpredictable
weights = np.random.random((3,1))
weights

array([[0.5881308 ],
       [0.89771373],
       [0.89153073]])

In [7]:
input_layer = training_inputs
mul = np.dot(input_layer,weights)
mul

array([[0.89153073],
       [2.37737526],
       [1.47966153],
       [1.78924446]])

In [8]:
print(input_layer.shape)
print(weights.shape) 

(4, 3)
(3, 1)


In [9]:
outputs = activation(mul)
outputs.round()

array([[1.],
       [1.],
       [1.],
       [1.]])

In [0]:
def gradient(x):
  return x * (1-x)

In [0]:
for i in range(500):
  input_layer = training_inputs

  # Multiplying the input layer matrix withthe weight matrix 
  mul = np.dot(input_layer,weights)
  outputs = activation(mul)
  
  # Applying the gradient descent
  error = training_outputs - outputs
  adjustments = error * gradient(outputs) ### gradient descent
  
  weights += np.dot(input_layer.T,adjustments)
  # print("ADJUSTMENTS :" , adjustments)

In [12]:
weights

array([[ 6.49807133],
       [-0.22503222],
       [-3.02759398]])

In [13]:
outputs.round()

array([[0.],
       [1.],
       [1.],
       [0.]])